# Generated by Django 2.2.15 on 2020-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='lines',
            old_name='freq',
            new_name='input_freq',
        ),
        migrations.RenameField(
            model_name='lines',
            old_name='number',
            new_name='output_freq',
        ),
    ]
