# Generated by Django 2.2.15 on 2020-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200913_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registers',
            old_name='value',
            new_name='default_value',
        ),
        migrations.AddField(
            model_name='lines',
            name='default_input_freq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lines',
            name='default_output_freq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
