# Generated by Django 2.2.15 on 2020-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200913_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
