# Generated by Django 2.2.15 on 2020-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registers_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='default_status',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
