# Generated by Django 2.2.15 on 2020-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lines_turn_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='default_turn_on',
            field=models.BooleanField(default=False),
        ),
    ]
