# Generated by Django 2.2.15 on 2020-11-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lines_default_turn_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='default_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registers',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
