# Generated by Django 2.2.15 on 2020-11-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201116_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
